---
title: "Ensemble Models"
author: "Nick Wawee"
date: "3/26/2021"
output: word_document
---

## Loading

```{r setup, include=T}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
source('/Users/nickwawee/Desktop/BGSU/MSA_6440/Week_2/myfunctions.R')
library(caret)
library(ada)
library(mlearning)
library(plyr)

plot_cm = function(confusion){#https://gist.github.com/ctokheim/c3ab56a4db7311487761
  tile <- ggplot() + geom_tile(aes(x=Actual, y=Predicted, fill=Percent),
                               data=confusion, color="black",size=0.1) + 
                     labs(x="Actual",y="Predicted") +  # axis labels
                     opts(axis.text.x = theme_text(angle=-90))  # rotate axis ticks text
  tile <- tile + geom_text(aes(x=Actual,y=Predicted, label=sprintf("%.1f", Percent)),
                           data=confusion, size=3, colour="black") + 
                 scale_fill_gradient(low="grey",high="red")  # low pcts are grey, high pcts are red
  tile <- tile + geom_tile(aes(x=Actual,y=Predicted),
                           data=subset(confusion, as.character(Actual)==as.character(Predicted)), 
                           color="black", size=0.3, fill="black", alpha=0)
  return(tile)
}
```



```{r loading}
bank = read.csv('../data/processed/BankChurners_filtered.csv', stringsAsFactors = T)

# Creating dummy variables for Education
bank$High_School <- ifelse(bank$Education_Level == 'High School', 1, 0)
bank$College <- ifelse(bank$Education_Level == 'College', 1, 0)
bank$Graduate <- ifelse(bank$Education_Level == 'Graduate', 1, 0)
bank$Uneducated <- ifelse(bank$Education_Level == 'Uneducated', 1, 0)
bank$Post_Graduate <- ifelse(bank$Education_Level == 'Post-Graduate', 1, 0)
bank$Doctorate <- ifelse(bank$Education_Level == 'Doctorate', 1, 0)

# Creating dummy variables for Marital Status
bank$Married <- ifelse(bank$Marital_Status == 'Married', 1, 0)
bank$Single <- ifelse(bank$Marital_Status == 'Single', 1, 0)
bank$Divorced <- ifelse(bank$Marital_Status == 'Divorced', 1, 0)

# Creating dummy variables for Gender
bank$Male <- ifelse(bank$Gender == 'M', 1, 0)
bank$Female <- ifelse(bank$Gender == 'F', 1, 0)

# Creating dummy variables for Income
bank$Income_5 <- ifelse(bank$Income_Category == '$120K +', 1, 0)
bank$Income_4 <- ifelse(bank$Income_Category == '$80K - $120K', 1, 0)
bank$Income_3 <- ifelse(bank$Income_Category == '$60K - $80K', 1, 0)
bank$Income_2 <- ifelse(bank$Income_Category == '$40K - $60K', 1, 0)
bank$Income_1 <- ifelse(bank$Income_Category == 'Less than $40K', 1, 0)

#Creating dummy variables for Card category
bank$Blue_Card <- ifelse(bank$Card_Category == 'Blue', 1, 0)
bank$Gold_Card <- ifelse(bank$Card_Category == 'Gold', 1, 0)
bank$Plat_Card <- ifelse(bank$Card_Category == 'Platinum', 1, 0)
bank$Silver_Card <- ifelse(bank$Card_Category == 'Silver', 1, 0)

bank <- bank[,c(-1,-2,-5,-7:-10)]

RNGkind (sample.kind = "Rounding") 
set.seed(0)

dfls = partition.2(bank, 0.7)

test.data = dfls$data.test
training.data = dfls$data.train
```

## Random Forest

```{r rf}
set.seed(0)
modelLookup("rf")
train_control <- trainControl(method="cv", number=10)
rf <- train(Attrition_Flag ~ ., data = training.data, method = "rf", ntree = 50,rControl = train_control, tuneGrid = expand.grid(mtry = c(2,5,8)), metric = 'Kappa')


print(rf)
plot(varImp(rf))

rf$finalModel

# get prediction on the test data
pred.test.rf = predict(rf$finalModel, test.data, type = 'class')

# create confusion matrix
cm = confusionMatrix(pred.test.rf, test.data$Attrition_Flag, positive = "Attrited Customer")

confusion = data.frame(cm)
confusion = ddply(cm, "Actual", transform, Percent = Freq / sum(Freq))

cm_plot = plot_cm(confusion)

cm_plot
```

## ADABoost

```{r adaboost}
modelLookup("ada")
set.seed(0)
train_control <- trainControl(method="cv", number=10)

tgrid <- expand.grid(iter = c(50,100,150),         
                      maxdepth = c(1, 2, 3),       
                      nu = c(0.1,0.2))
ada <- train(Attrition_Flag~ . , data = training.data, method = "ada", metric = "Kappa",
                trControl = train_control, tuneGrid = tgrid)
print(ada)
plot(varImp(ada))

# get prediction on the test data
pred.test.ada = predict(ada$finalModel, test.data)

# create confusion matrix
cm = confusionMatrix(pred.test.ada, test.data$Attrition_Flag, positive = "Attrited Customer")

confusion = data.frame(cm)
confusion = ddply(cm, "Actual", transform, Percent = Freq / sum(Freq))


```
