---
title: "Models"
output: word_document
---

```{r}
Bank <- read.csv("~/Desktop/MSA_6440/customer_churn/data/processed/BankChurners_filtered.csv")
source('/Users/JonathanVoth/Desktop/R Codes/myfunctions.R')

bank <- Bank[,c(-1,-2)]

RNGkind (sample.kind = "Rounding") 
set.seed(0)
p2 <- partition.2(bank, 0.7) # 70:30 partition
training.data <- p2$data.train
test.data <- p2$data.test
```

## Logistic Regression
```{r}
# Logistic model with all variables
log.model <- glm(Attrition_Flag ~ ., family = binomial(link='logit'), data = training.data)
summary(log.model)

step.model <- step(log.model)
step.model$coefficients

library(car)
vif(step.model)
```

## CV Logistic Model
```{r}
library(caret)
# K-fold Cross Validation
set.seed(0)
train_control <- trainControl(method = "cv", number = 10) 
step_cv <- train(Attrition_Flag ~ ., data = training.data, family = "binomial", method = "glmStepAIC", trControl = train_control)

print(step_cv)
step_cv$finalModel

# Confusion matrix for test data
prob.test <- predict(step_cv, newdata = test.data, type = "prob")
y.test <- ifelse(prob.test[,2] > 0.8, "Existing Customer", "Attrited Customer")
confusionMatrix(as.factor(y.test), as.factor(test.data$Attrition_Flag), positive = "Existing Customer")
```

## Decision Tree Model
```{r}
library(rpart)
library(rpart.plot)
library(caret)

# Decision tree model with CV
set.seed(0)
train_control <- trainControl(method = "cv", number = 10) 
tree_cv <- train(Attrition_Flag ~ ., data = training.data, method = "rpart", trControl = train_control, tuneGrid = data.frame(cp = seq(0, 0.01, 0.001)), metric = "Kappa", control = rpart.control(minsplit = 150, minbucket = 100))

print(tree_cv)

# Decision tree rules plot
prp(tree_cv$finalModel, type = 1, extra = 1, under = TRUE, split.font = 2, varlen = -10)

# Evaluation on the test data
prob.test <- predict(tree_cv, test.data, type = 'prob')
y.test <- ifelse(prob.test[,2] > 0.8, "Existing Customer", "Attrited Customer")
confusionMatrix(as.factor(y.test), as.factor(test.data$Attrition_Flag), positive = 'Existing Customer')
```

## Neural Network
```{r}
# Folds
set.seed(0)
train_control <- trainControl(method = "cv", number = 10)

tune.grid <- expand.grid(size = seq(from = 1, to = 10, by = 1), decay = seq(from = 0.1, to = 0.5, by = 0.1))

# Fitting NN model
cv.nn <- train(Attrition_Flag ~ . , data = training.data, method = "nnet", preProc = c("center", "scale"), trControl = train_control, tuneGrid = tune.grid, metric = "Kappa")

# Plot
plot(cv.nn)
# Best parameters
cv.nn$bestTune

# Evaluation on the test data
prob.test <- predict(cv.nn, test.data, type = 'prob')
y.test <- ifelse(prob.test[,2] > 0.8, "Existing Customer", "Attrited Customer")
confusionMatrix(as.factor(y.test), as.factor(test.data$Attrition_Flag), positive = 'Existing Customer')
```
