---
title: "Plots"
output: word_document
---

```{r}
Bank <- read.csv("~/Desktop/MSA_6440/customer_churn/data/processed/BankChurners_filtered.csv")
```

## Exploratory Plots
```{r}
# Plot of attrition flag
plot(Bank$Attrition_Flag)
library(plyr)
count(Bank, 'Attrition_Flag')
1113/7081 # Percent customer attrition

count(Bank, 'Card_Category')

library(ggplot2)
par(mfrow=c(2,2))
# Histogram of customer age
ggplot(Bank, aes(Customer_Age)) + geom_histogram(binwidth = 2) + geom_vline(aes(xintercept = mean(Customer_Age)), col = "red")
# Plot of gender
ggplot(Bank, aes(Gender)) + geom_bar()
# Plot of marital status
ggplot(Bank, aes(Marital_Status)) + geom_bar()
# Plot of education level
ggplot(Bank, aes(Education_Level)) + geom_bar()
ggplot(Bank, aes(Income_Category)) + geom_bar()
```


```{r}
# Histogram of months on book
ggplot(Bank, aes(Months_on_book)) + geom_histogram(binwidth = 4) + geom_vline(aes(xintercept = mean(Months_on_book)), col = "red")
# Histogram of credit limit
ggplot(Bank, aes(Credit_Limit)) + geom_histogram(binwidth = 1000) + geom_vline(aes(xintercept = mean(Credit_Limit)), col = "red")
# Histogram of average utilization ratio
ggplot(Bank, aes(Avg_Utilization_Ratio)) + geom_histogram(binwidth = 0.05) + geom_vline(aes(xintercept = mean(Avg_Utilization_Ratio)), col = "red")
```