---
title: "Undersampling Models"
output: word_document
---

```{r}
bank <- read.csv("../data/processed/BankChurners_filtered.csv")
source('/Users/nickwawee/Desktop/BGSU/MSA_6440/Week_2/myfunctions.R')

bank <- bank[,c(-1,-2,-10)]

RNGkind (sample.kind = "Rounding") 
set.seed(0)
p2 <- partition.2(bank, 0.7) # 70:30 partition
training.data <- p2$data.train
test.data <- p2$data.test

# Undersampling
set.seed(0)
all_exist <- training.data[which(training.data$Attrition_Flag == 'Existing Customer'),]
all_attrit <- training.data[which(training.data$Attrition_Flag == 'Attrited Customer'),]

random <- sample(1:nrow(all_exist), nrow(all_attrit), replace = FALSE)
train.data <- all_exist[random,]

training.under <- rbind(all_attrit, train.data)
table(training.under$Attrition_Flag)
```

```{r functions, include = F}
plot_cm <- function(cm, plot_title) {#https://stackoverflow.com/questions/23891140/r-how-to-visualize-confusion-matrix-using-the-caret-package

  layout(matrix(c(1,1,2)))
  par(mar=c(2,2,2,2))
  plot(c(100, 345), c(300, 450), type = "n", xlab="", ylab="", xaxt='n', yaxt='n')
  title(plot_title, cex.main=2)

  # create the matrix 
  rect(150, 430, 240, 370, col='#3F97D0')
  text(195, 435, 'Attrited', cex=1.2)
  rect(250, 430, 340, 370, col='#F7AD50')
  text(295, 435, 'Existing', cex=1.2)
  text(125, 370, 'Predicted', cex=1.3, srt=90, font=2)
  text(245, 450, 'Actual', cex=1.3, font=2)
  rect(150, 305, 240, 365, col='#F7AD50')
  rect(250, 305, 340, 365, col='#3F97D0')
  text(140, 400, 'Attrited', cex=1.2, srt=90)
  text(140, 335, 'Existing', cex=1.2, srt=90)

  # add in the cm results 
  res <- as.numeric(cm$table)
  text(195, 400, res[1], cex=1.6, font=2, col='white')
  text(195, 335, res[2], cex=1.6, font=2, col='white')
  text(295, 400, res[3], cex=1.6, font=2, col='white')
  text(295, 335, res[4], cex=1.6, font=2, col='white')

  # add in the specifics 
  plot(c(100, 0), c(100, 0), type = "n", xlab="", ylab="", main = "DETAILS", xaxt='n', yaxt='n', col = 'white')
  text(10, 85, names(cm$byClass[1]), cex=1.2, font=2)
  text(10, 70, round(as.numeric(cm$byClass[1]), 3), cex=1.2)
  text(30, 85, names(cm$byClass[2]), cex=1.2, font=2)
  text(30, 70, round(as.numeric(cm$byClass[2]), 3), cex=1.2)
  text(50, 85, names(cm$byClass[5]), cex=1.2, font=2)
  text(50, 70, round(as.numeric(cm$byClass[5]), 3), cex=1.2)
  text(70, 85, names(cm$byClass[6]), cex=1.2, font=2)
  text(70, 70, round(as.numeric(cm$byClass[6]), 3), cex=1.2)
  text(90, 85, names(cm$byClass[7]), cex=1.2, font=2)
  text(90, 70, round(as.numeric(cm$byClass[7]), 3), cex=1.2)

  # add in the accuracy information 
  text(30, 35, names(cm$overall[1]), cex=1.5, font=2)
  text(30, 20, round(as.numeric(cm$overall[1]), 3), cex=1.4)
  text(70, 35, names(cm$overall[2]), cex=1.5, font=2)
  text(70, 20, round(as.numeric(cm$overall[2]), 3), cex=1.4)
} 
```

## CV Logistic Model
```{r, include=FALSE}
library(caret)
# K-fold Cross Validation
set.seed(0)
train_control <- trainControl(method = "cv", number = 10) 
step_cv <- train(Attrition_Flag ~ ., data = training.under, family = "binomial", method = "glmStepAIC", trControl = train_control)
```

```{r cars}
print(step_cv)
step_cv$finalModel

save(step_cv, file = '../data/processed/logit_under.rda')
# Confusion matrix for test data
prob.test <- predict(step_cv, newdata = test.data, type = "prob")
write.csv(x = prob.test, file = '../data/processed/logit_prob_under.csv')
y.test <- ifelse(prob.test[,2] > 0.6, "Existing Customer", "Attrited Customer")
cm = confusionMatrix(as.factor(y.test), as.factor(test.data$Attrition_Flag), positive = "Existing Customer")

png('../plots/cm_logit_under.png', height = 6, width = 6, res = 600, units = 'in')
plot_cm(cm, 'Confusion Matrix: Logit - Under Sampled' )
dev.off()
```

## Decision Tree

```{r}
library(rpart)
library(rpart.plot)
library(caret)

# Decision tree model with CV
set.seed(0)
train_control <- trainControl(method = "cv", number = 10) 
tree_cv <- train(Attrition_Flag ~ ., data = training.under, method = "rpart", trControl = train_control, tuneLength = 10, metric = "Kappa", control = rpart.control(minsplit = 150, minbucket = 100))

print(tree_cv)

# Decision tree rules plot
prp(tree_cv$finalModel, type = 1, extra = 1, under = TRUE, split.font = 2, varlen = -10)

# Evaluation on the test data
prob.test <- predict(tree_cv, test.data, type = 'prob')
write.csv(x = prob.test, file = '../data/processed/cct_prob_under.csv')
y.test <- ifelse(prob.test[,2] > 0.6, "Existing Customer", "Attrited Customer")
confusionMatrix(as.factor(y.test), as.factor(test.data$Attrition_Flag), positive = 'Existing Customer')
```

## Neural Network
```{r, include=FALSE}
# Folds
set.seed(0)
train_control <- trainControl(method = "cv", number = 10)

tune.grid <- expand.grid(size = seq(from = 1, to = 10, by = 1), decay = seq(from = 0.1, to = 0.5, by = 0.1))

# Fitting NN model
cv.nn <- train(Attrition_Flag ~ . , data = training.under, method = "nnet", preProc = c("center", "scale"), trControl = train_control, tuneGrid = tune.grid, metric = "Kappa")
```

```{r}
# Plot
plot(cv.nn)
# Best parameters
cv.nn$bestTune

# Evaluation on the test data
prob.test <- predict(cv.nn, test.data, type = 'prob')
write.csv(x = prob.test, file = '../data/processed/nn_prob_under.csv')
y.test <- ifelse(prob.test[,2] > 0.65, "Existing Customer", "Attrited Customer")
confusionMatrix(as.factor(y.test), as.factor(test.data$Attrition_Flag), positive = 'Existing Customer')
```

